version: "3"
services: 
  postgresql:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: api-laravel
    volumes:
      - pg-data-api-laravel:/var/lib/postgresql/data

volumes:
  pg-data-api-laravel: